- hosts: localhost
  tasks:
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/R.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/thirdparty.yml
