- hosts: localhost
  vars:
    sshkey: "{{ lookup('env', 'HOME')}}/.ssh/id_ed25519"
    home: "{{ lookup('env', 'HOME')}}"
    pythonversion: "3.10.5"
  tasks:
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/R.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/thirdparty.yml
    - import_tasks: tasks/i3.yml
    - import_tasks: tasks/python.yml
    - import_tasks: tasks/golang.yml
