- hosts: localhost
  vars:
    home: "{{ lookup('env', 'HOME')}}"
    repos: "{{ lookup('env', 'HOME')}}/repos"
    pythonversion: "3.10.5"
  tasks:
    - import_tasks: tasks/core-ubuntu.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/neovim-ubuntu.yml
    - import_tasks: tasks/rust.yml
    - import_tasks: tasks/starship.yml
    - import_tasks: tasks/R-ubuntu.yml
    - import_tasks: tasks/python.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/obsidian.yml
