- hosts: localhost
  vars:
    sshkey: "{{ lookup('env', 'HOME')}}/.ssh/id_ed25519"
    home: "{{ lookup('env', 'HOME')}}"
    pythonversion: "3.10.5"
  tasks:
    - import_tasks: tasks/core-ubuntu.yml
    - import_tasks: tasks/i3.yml
