- name: check clj installed
  tags: 
    - install
    - clojure
  ansible.builtin.stat:
      path: "/usr/local/bin/clj"
  register: clj_st

- name: clojure install dependencies
  become: true
  tags: 
    - install
    - clojure
  ansible.builtin.package:
    name:
      - rlwrap
    state: "present"

- name: clojure download installer
  tags:
    - install
    - clojure
  ansible.builtin.shell: "cd {{ home }}/Downloads && curl -O https://download.clojure.org/install/linux-install-1.11.1.1155.sh && chmod +x {{ home }}/Downloads/linux-install-1.11.1.1155.sh"
  when: clj_st.stat.exists == False

- name: clojure clj install
  tags:
    - install
    - clojure
  ansible.builtin.shell: "{{ home }}/Downloads/linux-install-1.11.1.1155.sh"
  when: clj_st.stat.exists == False
