- name: install i3 and packages
  become: true
  tags: 
    - install
    - i3
  package:
    name:
      - xrandr
      - nitrogen
      - dunst
      - i3-gaps
      - rofi
      - polybar
      - picom

