- name: install neovim build dependencies
  become: true
  tags: neovim
  package:
    name:
      - ninja-build
      - cmake
      - gcc
      - gettext
    state: "latest"

- name: clone neovim
  tags: neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ repos }}/neovim"
    force: true

- name: checkout neovim nightly
  tags: neovim
  shell: "cd {{ repos }}/neovim && git checkout nightly"

- name: build neovim
  tags: neovim
  shell: "cd {{ repos }}/neovim && make distclean && make CMAKE_BUILD_TYPE=Release"

- name: install neovim
  tags: neovim
  become: true
  shell: "cd {{ repos }}/neovim && make install"

