- name: install neovim build dependencies
  become: true
  tags: neovim
  package:
    name:
      - ninja-build
      - libtool
      - autoconf
      - automake
      - cmake
      - gcc
      - gcc-c++
      - make
      - pkgconfig
      - unzip
      - patch
      - gettext
      - curl
    state: "latest"

- name: get packer.nvim
  tags: neovim
  ansible.builtin.git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1

- name: clone neovim
  tags: neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ lookup('env', 'HOME') }}/dev/neovim"
    force: yes

- name: checkout neovim nightly
  tags: neovim
  shell: "cd {{ lookup('env', 'HOME') }}/dev/neovim && git checkout nightly"

- name: build neovim
  tags: neovim
  shell: "cd {{ lookup('env', 'HOME')}}/dev/neovim && make distclean && make CMAKE_BUILD_TYPE=Release"

- name: install neovim
  tags: neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME')}}/dev/neovim && make install"
