- name: install neovim build dependencies
  become: true
  tags: neovim
  package:
    name:
      - ninja-build
      - libtool
      - autoconf
      - automake
      - cmake
      - gcc
      - gcc-c++
      - make
      - pkgconfig
      - unzip
      - patch
      - gettext
      - curl
    state: "latest"

- name: get packer.nvim
  tags: neovim
  ansible.builtin.git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ home }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1

- name: clone neovim
  tags: neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ home }}/dev/neovim"
    force: true

- name: checkout neovim nightly
  tags: neovim
  shell: "cd {{ lookup('env', 'HOME') }}/dev/neovim && git checkout nightly"

- name: build neovim
  tags: neovim
  shell: "cd {{ home }}/dev/neovim && make distclean && make CMAKE_BUILD_TYPE=Release"

- name: install neovim
  tags: neovim
  become: true
  shell: "cd {{ home }}/dev/neovim && make install"

- name: clone lua language server
  tags:
    - neovim
    - lua
  ansible.builtin.git:
    repo: "https://github.com/sumneko/lua-language-server"
    dest: "{{ home }}/lua-language-server"
    depth: 1

- name: lua language submodules
  tags:
    - neovim
    - lua
  shell: "cd {{ home }}/lua-language-server && git submodule update --depth 1 --init --recursive"

- name: install lua lsp
  tags:
    - neovim
    - lua
  shell: "cd {{ home }}/lua-language-server/3rd/luamake && ./compile/install.sh && cd {{ home }}/lua-language-server && ./3rd/luamake/luamake rebuild"

