- name: check pyenv installed
  tags: 
    - install
    - python
  ansible.builtin.stat:
      path: "{{ home }}/.pyenv/bin/pyenv"
  register: pyenv_st

- name: clone pyenv
  tags: 
    - install
    - python
  ansible.builtin.git: 
    repo: "git@github.com:pyenv/pyenv.git"
    dest: "{{ home }}/.pyenv"
  when: pyenv_st.stat.exists == False

- name: python install dependencies
  become: true
  tags: 
    - install
    - python
  package:
    name:
      - make 
      - gcc 
      - zlib1g-dev
      - bzip2 
      - libbz2-dev
      - libssl-dev
      - tk-dev
      - libffi-dev
      - xz-utils
    state: "present"

- name: build pyenv
  tags: 
    - install
    - python
  shell: "cd {{ home }}/.pyenv && src/configure && make -C src"
  when: pyenv_st.stat.exists == False

- name: check pyenv python installed
  tags: 
    - install
    - python
  ansible.builtin.stat:
      path: "{{ home }}/.pyenv/versions/{{ pythonversion }}"
  register: pyenv_python_st

- name: install python with pyenv
  tags: 
    - install
    - python
  shell: "pyenv install {{ pythonversion }}"
  when: pyenv_python_st.stat.exists == False

- name: set default python version
  tags: 
    - install
    - python
  shell: "pyenv global {{ pythonversion }}"

- name: Install pipx
  tags: 
    - install
    - python
  shell: "pip install pipx --user"

- name: Install pipenv
  tags: 
    - install
    - python
  shell: "pipx ensurepath && pipx install pipenv"
