- name: install r programming language
  become: true
  package:
    name:
      - R
      - rstudio-desktop

- name: set cran mirror
  shell: "touch {{ lookup('env', 'HOME') }}/.Rprofile && echo \"options(repos=structure(c(CRAN='http://cran.r-project.org')))\" >> {{ lookup('env', 'HOME') }}/.Rprofile"
